### ISSUE TITLE
DKIM not signing emails

### ISSUE THREAD

**Issue by christopher-kapic** [LukeSmithxyz/emailwiz#117]
Hi Luke/all,

I retried installing the server and _almost_ have it working. It just won't DKIM sign my emails. Here is the output for DKIM on appmaildev.com:
`DKIM-Result: none (no signature)`.

I made sure to copy the TXT records exactly, but it still isn't working. Any idea what I can do?

Thank you!

**Comment by LukeSmithxyz** [comment]
What is your registrar? It might want a truncated host for the entry or something like just `mail._domainkey` or something. Either way, something is probably just misplaced in the DNS settings.

**Comment by adrientremblay** [comment]
What was the solution @christopher-kapic ?

**Comment by christopher-kapic** [comment]
I'm sorry @adrientremblay, I don't think I ever got it working, and even if I did there were other problems. I have decided to fold on self-hosting email and am currently using Zoho mail. Email is a PITA, and if I need to do something privately I can communicate in person or with other options.

**Comment by adrientremblay** [comment]
@christopher-kapic Alright. Thanks for the reply.

Took a break and looked at it again today. So it seems the problem was that I had
`
*@mail.adrientremblay.xyz mail._domainkey.adrientremblay.xyz
*@mail.adrientremblay.com mail._domainkey.adrientremblay.com
`
instead of 
`
*@adrientremblay.xyz mail._domainkey.adrientremblay.xyz
*@adrientremblay.com mail._domainkey.adrientremblay.com
`
In my /etc/postfix/dkim/signingtable for whatever dumb reason (my mistake). Once I sorted this out, and made sure my dns entries were using the right key things worked. I used the value from /etc/postfix/dkim/mail.txt I just removed the quotation marks and spaces.

**Comment by christopher-kapic** [comment]
Thanks @adrientremblay. If I ever decide to revisit this, it will be hats off to you.

**Comment by adrientremblay** [comment]
Hey @christopher-kapic! Yeah the problem may be something completely seperate for you. But I would double check the files you have modified, check if your opendkim service is indeed running without fault, and if so really double check your DNS stuff. :)
