### ISSUE TITLE
What's the "right" way to setup the $maildomain LetsEncrypt certificate?

### ISSUE THREAD

**Issue by darthdeus** [LukeSmithxyz/emailwiz#14]
I'm not really sure how LetsEncrypt works with generating SSL certificates for non-HTTP domains. Since you mention you use *Debian web server*, does that mean that you're generating the certificate via some default Apache configuration? Or should we use some variant of `certbot certonly`?

I've found different answers on the web and haven't really found one that didn't look like a hack, so I'm curious how you suggest doing it. Thanks!

**Comment by LukeSmithxyz** [comment]
Well to be honest, I wouldn't know: I really only intended this for use with a domain. I _think_ that certbot can assign certificates to IP addresses alone... so you might be able to just substitute the IP address for the domain.

So I can't tell you for sure. You probably wouldn't be breaking anything by just running this script then `apt purge`ing the settings if they don't work and trying something a little different.

**Comment by kroppt** [comment]
You can use `caddy` to generate and keep up to date your certificates. That's what I did.
You can also specify an IP address, but I have not tested that myself.

Here is how I configured it (`/etc/caddy/Caddyfile`)
```
mail.mydomain.com // or your IP address

tls my.email@address.com

respond 403
```
I added the last line so you don't get a blank 200 when browsing to the site. This only required the HTTPS port to be open (443).

I verified that my setup shows as secure in the browser when navigating to the site.

Once configured, you can run `caddy` as a service, and it will keep your certificates up to date.

You will need to change Luke's script, though, because the keys are stored in a separate place.
```
/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.mydomain.com/mail.mydomain.com.crt
/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.mydomain.com/mail.mydomain.com.key
```
I haven't gotten to testing my mail server setup yet, but I think you should also use `CApath` rather than `CAfile` in the `postconf` configuration, which can be gotten from the JSON in the same directory listed above (I think!):
```
...
    "certUrl": "https://acme-v02.api.letsencrypt.org/acme/cert/..."
...
```

**Comment by LukeSmithxyz** [comment]
So okay, the script works a little differently now so I'm going to close this.

If you run it now, *do not* make a dummy `mail.` domain: it should be using the certbot certificate of your root website.

I think if you do make and get a cert for `mail.` before running it should still work, just make sure to get it before if you do.

I'll be updating the dox soon.
