### ISSUE TITLE
Configuration with subdomain

### ISSUE THREAD

**Issue by jcrcx** [LukeSmithxyz/emailwiz#151]
Hi,

Is there a way to configure an email server with for example: user@sub.domain.com ?

The configuration in my DNS Records is done with A and AAAA records, also with CNAME, MX and TXT.

A/AAAA -> (www.)sub.domain.com (Server IP Address)
CNAME -> mail.sub.domain.com (points to > sub.domain.com)
MX -> mail.sub.domain.com
TXT -> output given by the script with the initial domain of sub.domain.com

Can someone tell me how to configure it correctly

(it is valid to laugh if I did something stupid)

**Comment by bionor** [comment]
I'm wondering about the same. I have office 365 mail that is associated with domain.com and I'm trying setup an extra mail server at mail.domain.com.

I'm getting connection refused though, which I wonder might mean the issue is something else. Cannot understand why connections are refused. There is no firewall as of yet and ports are open

**Comment by LukeSmithxyz** [comment]
You can manually go into the settings in play with it, but as is, the script will not do this by default as it's not really my intent.
