### ISSUE TITLE
mail going straight to spam because of .xyz

### ISSUE THREAD

**Issue by danielfan61a** [LukeSmithxyz/emailwiz#162]
is the .xyz TLD dead? I used to send mail fine to google, i recently migrated my server and reinstalled everything.

when checking with https://www.mail-tester.com, I found that my domain name is "bad". 

can I do anything about this?
![tld](https://user-images.githubusercontent.com/86361358/129915200-fd7e1c83-3c30-4e5e-9c68-01a99d39ffbf.png)

**Comment by LukeSmithxyz** [comment]
Not relevant to this repo.

What do you mean by dead? -1.725 is nowhere near sufficient to mark mail as spam, so unless you don't have the rest of your server configured, it will not make a difference.

SA gives more scrutiny to xyz addresses since they are widely used in China for spam. If you are worried about that, check which SA is skeptical of and use a more traditional TLD.

**Comment by loganwoodxyz** [comment]
> Not relevant to this repo.
> 
> What do you mean by dead? -1.725 is nowhere near sufficient to mark mail as spam, so unless you don't have the rest of your server configured, it will not make a difference.
> 
> SA gives more scrutiny to xyz addresses since they are widely used in China for spam. If you are worried about that, check which SA is skeptical of and use a more traditional TLD.

Another thing to consider (at least from what I've read) is that IP addresses also play a role. If your IP address is associated with a VPS that has a bad or neutral reputation, you might be blocked by some recipient servers by default.

**Comment by r1bnc** [comment]
^ True, Digital Ocean and OVHCloud has those problems.
