### ISSUE TITLE
Anyone can send mails from a local user as long as the recipient is another local user

### ISSUE THREAD

**Issue by william-stacken** [LukeSmithxyz/emailwiz#237]
I got a spam mail recently with a valid DKIM signature from my admin user to one of my other users. At first I thought I was compromised, but after some quick testing with openssl I noticed that it is possible for anyone to send such a mail without providing a password.

I found a solution to this problem, see https://serverfault.com/questions/318334/how-to-enforce-sender-address-to-be-logged-in-userexample-org-in-postfix/318432#318432

**Comment by LukeSmithxyz** [comment]
I'm pretty sure that the commit the other week b657e768c9f9a9773b7767b286d1b16603ecd4ae should solve this problem since it requires a helo over smtp and puts specific authentication restrictions on domains and accounts.

I've been aware that you can use openssl/telnet to send an "anonymous" mail to a user from "their own" address like this. I've tried doing this with the new settings and it is not possible. This should fix people using this exploit for spam as well.

**Comment by adastx** [comment]
Side note: is there a recommended way to update emailwiz? I just ran mailrm.sh and reinstalled, but is there a better way?

**Comment by sssemil** [comment]
The issue still persists. Fixed on my side with this - https://serverfault.com/a/321127/282508. However, you can still spoof any other domain, like `noreply@fedex.com` for example. Not sure how to deal with that at the moment. I guess something like what's in this PR - https://github.com/LukeSmithxyz/emailwiz/pull/238 should help with spoofing self.
