### ISSUE TITLE
Backscatter

### ISSUE THREAD

**Issue by SelfAdjointOperator** [LukeSmithxyz/emailwiz#239]
Is anyone else getting backscatter on their server?
That is: An attacker sends mail to my server `my-server.com` with
`Address=user@some-domain-i-dont-handle.com`
and
`Reply-To=blah@gmail.com`
which tricks my server into sending the undeliverable email to `gmail.com`. When repeated enough, this looks like a DOS attack from the recipient's end, and I inevitably get my domain `my-server.com` blacklisted by `gmail.com`

I noticed [these](https://github.com/LukeSmithxyz/emailwiz/commit/b657e768c9f9a9773b7767b286d1b16603ecd4ae) recent additions but it still doesn't stop backscatter
My current 'solution' is
1) to change the `bounce` and `defer` services in `/etc/postfix/master.cf` to use the `discard` command, which stops the messages from being stored in `~postfix/deferred/` and postfix keep trying to send them to say `gmail.com`, but I'm still eventually getting blocked for 'spamming'
2) keep checking `journalctl -ef` and manually blocking ips that are sending me the dodgy emails with `ufw`

Postfix's [documentation on backscatter](https://www.postfix.org/BACKSCATTER_README.html) isn't the best

I can still keep receiving emails / set up accounts on websites with email addresses directed to my server, which is fine, but I wouldn't bank on using the accounts for outgoings, getting through big providers like gmail and outlook etc. I think I'll be sticking with outlook for personal outgoing mail :/

---

Sidenote / siderant: the absolute state of setting up a personal mail server:
- Postfix doesn't even have an official git repository; tarballs are just pumped out once in a while, _so_ secure
- Postfix's documentation isn't very clear and uses moronic esoteric syntax in `master.cf` where whitespace on supplementary lines matters, and terms like 'milter' instead of 'mail_filter'
- Insane defaults such as allowing older (insecure) versions of TLS
- Having to precariously configure postfix and dovecot's symbiotic relationship with silly notation like `\Inbox`, again dovecot's esoteric `.conf` format where opening-brace-position matters. I personally use the one-true-brace-style so that's fine, but it's not the point.

I could go on... ~~Arch Linux feels really modern, Apache 2 as `httpd` running as `http`, systemd's consistency, whereas Debian's `apache2` running as `www-data` with boomer tier syslog-ging programs like `rsyslogd` instead of just logging to stderr and letting `systemd{,-journald}` do the rest. Debian also separates `bin` and `sbin`, ew. It feels so 90s/00s. It's what I expected Linux to be when I first moved from Windows, a fragile `rc`-file mess. Debian feels ancient compared to Arch, which is ironic considering that Debian's versioned releases give opportunities to slightly break compatibility between versions if it's worth doing so to keep the distro modern. I also don't have `cron` installed on Arch anymore. I don't need it! [systemd timers](https://www.freedesktop.org/software/systemd/man/systemd.timer.html) have the same `OnCalendar` capabilities as cron but also have so much more. The timer lifecycle is more well defined, the `.service` file corresponding to it being a systemd unit, not having events overlap each other if the service is running from the last time the timer triggered, using `systemd-journald`, environment managed by `systemctl set-environment`, whereas some versions of cron don't even set / export the `USER` environment variable in scripts by default (Vixie cron), and some do (cronie). Also `cron` runs all of its stuff in the system slice, using `setuid` to drop to the appropriate user, whereas systemd user timers run neatly within the user's slice.~~ tldr

If only there were a program, say `systemd-maild` that covered outgoing smtp, managing pop, imap etc all in one sane configurable program. inb4 some midwits saying 'breaking the Unix philosophy', because it wouldn't be: one good tool for the job: systemd-maild, instead of {postfix, dovecot, spamassassin, opendkim, apache2 (just for a dummy domain for SSL certificates), ...}. If I had 48 hours in a day (which I don't) I'd honestly consider writing an all-in-one mail daemon myself! Sane configuration file format eg `.json` or `.toml` (like systemd units), ideally just werks out of the box, with the same amount of configuration as is needed for `sshd` to get set up (not much).

The [Unix Haters Handbook](https://web.mit.edu/~simsong/www/ugh.pdf) has some funny bits, such as `rm *` calling `rm -r ...` if the first file the glob picks up is called `-r`, and some bits I disagree with, but one I very much agree with is Chapter 4 pt1 `Sendmail: The Vietnam of Berkeley Unix`. The absolute STATE of email.

Glad you created this emailwiz script though. I'd never in a thousand years have set this sh\*t up by myself.

**Comment by LukeSmithxyz** [comment]
Interesting issue you're having. Firstly, I would say having postfix deter the mail is a bad idea, and it should probably be rejecting it beforehand. Rejecting the mail properly is done on the initial connection with the fradulent attack server, so Gmail is never involved.

I was under the impression that `reject_unauth_destination` would be sufficient to avoid this issue, but you can take a look at other `smtpd_recipient_restrictions`, perhaps `reject_unknown_recipient_domain`?

**Comment by LukeSmithxyz** [comment]
I'm going to close this since the original poster seems to have ceased running his own server and I have no other way to troubleshoot. The two additional options I mentioned should deal with or mitigate the issue for other users and I've gone ahead and added them to the default configuration since they should not interfere with any personal email servers.

**Comment by SelfAdjointOperator** [comment]
Yeah this can be marked as closed I guess.
I'm still running a VPS (+ postfix etc). I've only had one backscatter incident since. If it's infrequent like this then I can just manually block attackers with `ufw` as and when needed.
Thanks, Luke

**Comment by mariansam** [comment]
I complety agree wit @SelfAdjointOperator's rant. I'm self-hosting a emailwiz-based mail server and it's pretty painful sometimes. Few months ago, about a million spam emails were sent through my server with my domain, because I have created a Linux user called `test` with password `test`. Apparently some bot found it and was able to log in and send email (tho the `test` user was not part of the `mail` group i think).

Sometimes my emails arrive to Gmail successfully, sometimes to spam, and sometimes they just don't and I get an auto reply that it was so spam it just got rejected.

---

I know some people are using Mail-in-a-box ([website](https://mailinabox.email/), [github](https://github.com/mail-in-a-box/mailinabox)), however I'm not a big fan of it as it's pretty old, not actively maintained and works pretty weirdly

At our company, we're using Mailcow ([website](https://mailcow.email/), [github](https://github.com/mailcow/mailcow-dockerized)), it bundles Postfix+Dovecot+friends in Docker and comes with SOGo webmail.

Some friends are using Maddy ([website](https://maddy.email/), [github](https://github.com/foxcpp/maddy)) and they seem to be pretty happy. It's written in Go (Golang) and aims to replace the Postfix+Dovecot+others hell we're in, it does everything by itself.

I have no experience with things like [modoboa](https://github.com/modoboa/modoboa), [Mailu](https://github.com/mailu/mailu) or the pretty popular [Docker Mailserver](https://github.com/docker-mailserver/docker-mailserver)

It might be worth looking at services like [SendGrid](https://sendgrid.com/) or [Mailgun](https://www.mailgun.com/) which may act as a proxy and guard you from receiving spam and sending spam.
