### ISSUE TITLE
My mails are going to spam in gmail

### ISSUE THREAD

**Issue by s0m3OnE47** [LukeSmithxyz/emailwiz#25]
Ran the test on https://www.appmaildev.com/en/dkim -> all tests pass
tested on mxtoolbox -> Its Blacklisted by SEM FRESH

Can this be the issue?

**Comment by s0m3OnE47** [comment]
![error](https://user-images.githubusercontent.com/36131030/85320029-79349180-b490-11ea-8a88-84c974c1d21e.png)

**Comment by s0m3OnE47** [comment]
I found that if the website is new then it is added to SEM FRESH. I will try again in next week.

**Comment by LukeSmithxyz** [comment]
I think I'll add documentation about this in the readme when I get the chance.

**Comment by rmwalk** [comment]
@s0m3OnE47 it's been a week for you, do your messages still get sent to spam? I'm wondering that because my domain is 4 days old and every provider I send emails to still redirects them to the spam box.

**Comment by s0m3OnE47** [comment]
Yes my mails are still going to spam. But it is no longer blacklisted.
[Current warnings](https://imgur.com/a/SjNmIm4)

**Comment by s0m3OnE47** [comment]
My rDNS is pointing to mail.domain.xyz
https://www.appmaildev.com/en/dkim -> all tests pass
Getting 10/10 on mail-tester.com
Domain is not blacklisted
[Current warnings on mxtoolbox](https://imgur.com/a/SjNmIm4)

Mail is flagged spam by multiple gmail accounts, hotmail acc.
Setup similar to unaboomer.com

**Comment by rmwalk** [comment]
Yep, everything's ok with mine as well. It passes all the tests and my rDNS is pointing to the right domain.
Outlook, Protonmail and Tutanota  are flagging my mails as spam, although gmail is kind of weird about it. Some get sent directly to the inbox, some get sent to spam.
Yahoo mail is good though, every message I sent to them went to the inbox.

All in all everything is OK, I just need to tell people beforehand to look into the spam folder just in case they don't get it in the inbox.

**Comment by rmwalk** [comment]
So I actually purged everything and did it all over again from scratch but with another domain. I added my rDNS and took all the tests before sending any emails. When everything looked fine, I started testing and right off the bat all messages went to the recipient's inbox, except for Microsoft stuff like @outlook, @live etc.
Maybe gmail was still considering my first domain as spam because it had been flagged as such before and even though I had reconfigured everything, it still treated my messages as spam. With the new domain though everything is great, even emails sent to Protonmail, which sometimes didn't even let my messages through, are being delivered to the inbox.

**Comment by DJAndries** [comment]
Also experiencing similar issues when sending mail to the big guys (Gmail, Outlook/Hotmail). Emails only appear in the inbox if the recipient has sent an email to me before, or if they whitelisted my email.
Small guys (like protonmail) are okay, go right to the inbox.

DKIM, SPF, DMARC all pass. mxtoolbox and appmaildev like me. rDNS record has been propagated.

My mail server is fairly new, and I am aware that Gmail and Outlook keep a "reputation" for SMTP servers (especially new ones). Right now, I'm trying to "warm up" my server so that my server gains rep. Right now, that involves sending emails to my old personal email/alternate email accounts, replying to said emails, and emailing other people I know.

This guide shows a very systematic guide for warming up an IP: https://blog.h-educate.com/warm-up-smtp/
It seems that the guide is geared towards email servers that send promotional content, rather than transactional email, so sending tens of thousands of emails like the guide mentions is probably not necessary.
