### ISSUE TITLE
Add spamassassin cronjob. Do dovecot fail2ban jails need fixing? Add another jail to block imap-login attempts

### ISSUE THREAD

**Issue by VimBowen** [LukeSmithxyz/emailwiz#264]
I'm sure there may be a valid reason, but I think it would be wise to enable the included spamassassin cronjob to get the most up to date filters.

The emailwiz.sh would just need to change `CRON=0` to `CRON=1` in the file `/etc/default/spamassassin`

Also, I'm not sure if the dovecot/sieve fail2ban jails work properly. By default dovecot logs to syslog - [https://doc.dovecot.org/admin_manual/logging/](url). Running the suggested command seems to show my dovecot logs all point to the same ones as postfix. Therefore I believe, the `emailwiz.local` would need to specify the correct log for dovecot and sieve in order for those jails to work - I may of course be completely wrong about this.

I keep getting annoying errors about 'imap-login' a solution is here - [https://wiki.dovecot.org/HowTo/Fail2Ban](url)

**Comment by LukeSmithxyz** [comment]
Are you sure fail2ban isn't active? On my machine, the `jail.conf` automatically calls `paths-debian.conf` which sets the mail log to `/var/log/mail.log` and that variable should be read by the Dovecot and Postfix modules automatically as their profiles show. That documentation is assuming a fresh install, while Debian deploys a lot of defaults.

**Comment by VimBowen** [comment]
> 

Yeah fail2ban is active, as I added an sshd jail and that seems to be blocking just fine. I'll reset the `emailwiz.local` back to stock to see if it picks up dovecot bans, it's entirely possible I'm in a muddle - so I'll verify `jail.conf` and `paths-debian.conf` etc.

I'm still convinced though that this [https://wiki.dovecot.org/HowTo/Fail2Ban](url) may not be implemented. I know your script doesn't add it, so are you under the impression debian sets this up automatically? It's just so far, having manually set the log path to `/var/log/mail.log` for the dovecot jail, my mail log still has 'imap-login errors' and I have yet to see fail2ban block anything to do with dovecot, yet it seems to block postfix stuff just fine. In anycase, I added the filter in the link last night as well as the jail and will check in a bit whether it worked or not.

I don't know, maybe that's a bit beyond the scope of the script 🤷🏼‍♂️

In anycase, I'll report back later when I get a chance.

**Comment by LukeSmithxyz** [comment]
Check Debian's default Dovecot filter file. It's a lot more complete than that URL and it's there by default. I'm pretty sure it's being properly called and the log is referenced the same way as the Postfix file is. I guess I could be wrong, but it seems like it's set up the way it's supposed to be.

If your reason for thinking Dovecot isn't being blocked is because your fail2ban isn't blocking stuff, that's perfectly expected because hackers are *much* more likely to attempt to spam or hack Postfix than they are to try to download your mail with Dovecot.

**Comment by LukeSmithxyz** [comment]
I.e. just check your system logs where Dovecot is being logged and you will see for every one failed attempt to log into Dovecot, you'll probably have hundreds of attempts to log into or spam Postfix.

**Comment by VimBowen** [comment]
Thanks, I appreciate what you're saying. Still, I seem to be getting strange logs that are not banned.

Example:
`dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=XX.XX.XX.XX, lip=XX.XX.XX.XX, TLS, session=<sdhWDd321dwd>`

Or:
`dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=XXXX:XXXX:XXXX::XX, lip=XXXX:XXXX:XXXX:XXXX:XXXX:XXX:XXXX:XXXX, TLS handshaking: SSL_accept() failed: error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher, se
ssion=<wkjndwkWEEEEEEEwjndwQ>`

Neither the default dovecot filter nor the one I created using the previous website seems to block these IPs. Is this something to be concerned about? Thanks again.

**Comment by LukeSmithxyz** [comment]
Fail2ban depends on the frequency of failed logins. If they are separated enough or from different IPs, it's not going to block them. So if you are getting repeated attempts from the same IP in a row, fail2ban might not be active, but I'm looking at my logs now and while I have the same errors, they are spaced in time and from different IPs.

Otherwise, if you mistyped your password or username once, you would be blocked from your own server, etc.

**Comment by VimBowen** [comment]
For sure, but I've a few IPs try like 10-15 times in a row within seconds, so I would have expected it to be banned.

Anyway, I did a little digging looked at the the default debian dovecot filter as yoy suggested and having decyphered the failregex (could they make that any harder to read?) I'm guessing the aggressive mode is what would block the IP addresses in the above log example. I'll give that ago.

Thanks for the help and sanity check, take care now! Also thanks for making the script.
