### ISSUE TITLE
Question: what to do to backup and restore?

### ISSUE THREAD

**Issue by ciori** [LukeSmithxyz/emailwiz#270]
Hello, as I understand this is pretty much a "run and forget" type of install, it cannot be re-executed to update it or change configuration, but I love the idea that it is simple (no web gui or other stuff, just plain email).

For this reason, I wanted to ask how one would backup this mail server, are there particular steps one should take (for example create an archive of particular conf files)?

Let's say I need to migrate the server or reinstall it from scratch, (and let's say I don't care about backing up emails), can I just execute the script on the new machine (using the same domain name), or do I need to "import" the same configurations, keys, etc...?
This last question is to understand whether, upon a fresh install, the mail server will continue to operate as before, or if because of the new certificates, keys and dns entries it could be treated as a new one and therefore risks getting treated as spam.

Thank you.

**Comment by LukeSmithxyz** [comment]
Basically all you need to back up are the individual mail files, and the script recreates everything else almost always the same, but note this:

- You will need to read user accounts with `useradd` and `passwd`. You can't just copy and paste this since it is an aspect of the system at large.
- The OpenDKIM private key will change in a new installation, so you will have to change the OpenDKIM DNS entry. You could theoretically copy and paste this, but for different reasons, I would say that would be ill-advised. Just have the script generate a new one and edit the DNS setting.
- The location of your SSL certificate may change, but if the script is generating this itself, it shouldn't make a difference and you can just run the script and forget about it.
