### ISSUE TITLE
Solution for multiple domains on one server?

### ISSUE THREAD

**Issue by TDavLinguist** [LukeSmithxyz/emailwiz#38]
What should I do if I have successfully run emailwiz for one domain but also want to set up another mail domain? Should I just set the variable $domain to "domain.xyz" and let it run? I imagine that would possibly override the current configuration. Has anyone else tried to do this successfully using the script, or will I have to manually set up my second domain?

Thank you.

**Comment by LukeSmithxyz** [comment]
Yeah, it would be overwriting the configuration.

Due to how this email setup works, it using PAM and standatd Unix users
to log in. This is very nice because it doesn't have to use a SoyQL
database or anything, but it might be an issue because let's say I have
one email address luke@lukesmith.xyz and also luke@larbs.xyz on the same
server. The issue is that they would both be logging in simply as "luke"
so would have the same account.

So I think you'd have to have either a database setup for that or
something different.

Now you might be able to *alias* the mail from one domain to another: so
that if you want, luke@lukesmith.xyz and @larbs.xyz go to the same
account. That might be easier, but I can't give you immediate directions
on how to do that because I've never done it.
On 20/06/27 07:13AM, Tyler D. Davis wrote:
> What should I do if I have successfully run emailwiz for one domain but also want to set up another mail domain? Should I just set the variable $domain to "domain.xyz" and let it run? I imagine that would possibly override the current configuration. Has anyone else tried to do this successfully using the script, or will I have to manually set up my second domain?
>
> Thank you.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/emailwiz/issues/38

--
https://lukesmith.xyz

**Comment by DJAndries** [comment]
Have successfully added a second domain to my mail server created by this script.

For DKIM, you'll want to append an entry to allow signing for your second domain in `/etc/postfix/dkim/signingtable`. Should be fine to reuse your DKIM TXT entry on your main domain. Add something like `*@seconddomain.com mail._domainkey.maindomain.com`

Like Luke mentioned, you can create an alias so that you can map an email address to a user on your mail server. Adding a file called `/etc/postfix/virtual` and adding `me@seconddomain.com me-seconddomain` will ensure that mail is mapped to the `me-seconddomain` user on your machine.

A couple entries will need to be appended to main.cf:
```
virtual_alias_domains = seconddomain.com
virtual_alias_maps = hash:/etc/postfix/virtual
```
You'll need to run `sudo postmap /etc/postfix/virtual` to create the lookup db for the aliases.

Regarding DNS entries for your second domain, you'll need to add the exact same mail related records (MX and TXT) as your primary domain, with the exclusion of the DKIM record (since you'll be reusing the DKIM for your primary domain).

Hope that helps

**Comment by jrejaud** [comment]
> Have successfully added a second domain to my mail server created by this script.
> 
> For DKIM, you'll want to append an entry to allow signing for your second domain in `/etc/postfix/dkim/signingtable`. Should be fine to reuse your DKIM TXT entry on your main domain. Add something like `*@seconddomain.com mail._domainkey.maindomain.com`
> 
> Like Luke mentioned, you can create an alias so that you can map an email address to a user on your mail server. Adding a file called `/etc/postfix/virtual` and appending `me@seconddomain.com me-seconddomain` will ensure that mail is mapped to the `me-seconddomain` user on your machine.
> 
> A couple entries will need to be appended to main.cf:
> 
> ```
> virtual_alias_domains = seconddomain.com
> virtual_alias_maps = hash:/etc/postfix/virtual
> ```
> 
> You'll need to run `sudo postmap /etc/postfix/virtual` to create the lookup db for the aliases.
> 
> Regarding DNS entries for your second domain, you'll need to add the exact same mail related records (MX and TXT) as your primary domain, with the exclusion of the DKIM record (since you'll be reusing the DKIM for your primary domain).
> 
> Hope that helps

I followed your instructions and was able to get SMTP to work on the secondary domain. While I can connect to the mail server via IMAP, I don't see emails sent to emails on my secondary domain, can you elaborate as to how to get this to work, please?

**Comment by jrejaud** [comment]
I believe I figured it out.
The emails I was seconding to seconddomain.com were falling into the first domain's catch all email account :P . The instructions provided above did work for me, ty king.

**Comment by ollintzinlab** [comment]
It works on my side with @DJAndries method. Just how did you manage the SPF record? 
```
SPF-Record: v=spf1 mx a:mail.maindomain.com -all
Sender-IP: 216.128.130.224
Sender-Domain-Helo-Domain: seconddomain.com

Query TEXT record from DNS server for: seconddomain.com
[TXT]: v=spf1 mx a:mail.maindomain.com -all
Parsing SPF record: v=spf1 mx a:mail.maindomain.com -all

Mechanisms: v=spf1

Mechanisms: mx
Testing mechanism mx
Query MX record from DNS server for: seconddomain.com
Exception: Bad DNS packet
```
I think I misunderstood some steps

**Comment by ollintzinlab** [comment]
Forget about it, it was just a `TempError`. It's ok now.
