### ISSUE TITLE
DKIM Signature not working.

### ISSUE THREAD

**Issue by ulisesvina** [LukeSmithxyz/emailwiz#76]
I followed the tutorial step by step, as you can see in the screenshots. I performed a test right after doing the DNS settings and it's just not working as expected.

![](https://user-images.githubusercontent.com/20508563/93369603-3d059880-f815-11ea-9005-4318aecc936e.png)
![](https://user-images.githubusercontent.com/20508563/93369607-3d9e2f00-f815-11ea-8fdb-ef4adbe9b0ad.png)

**Comment by user234683** [comment]
Near the end of the script, did you see `Restarting opendkim...Job for opendkim.service failed because the control process exited with error code.`?
Or if you no longer have the console output, try running `systemctl start opendkim`. If it fails, then run `journalctl -xe` and check the lines below the beginning of the start process, after the line `Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter`. If you see `opendkim[176839]: opendkim: milter socket must be specified`, then your issue is [here](https://github.com/LukeSmithxyz/emailwiz/issues/42)

**Comment by ulisesvina** [comment]
It's not saying anything about "milter sockets". The output of `journalctl -xe` is:
`-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A stop job for unit opendkim.service has finished.
-- 
-- The job identifier is 9426 and the job result is done.
Oct 03 15:49:49 ubuntu-s-1vcpu-1gb-sfo2-01 systemd[1]: opendkim.service: Start request repeated too quickly.
Oct 03 15:49:49 ubuntu-s-1vcpu-1gb-sfo2-01 systemd[1]: opendkim.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit opendkim.service has entered the 'failed' state with result 'exit-code'.
Oct 03 15:49:49 ubuntu-s-1vcpu-1gb-sfo2-01 systemd[1]: Failed to start OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
-- Subject: A start job for unit opendkim.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit opendkim.service has finished with a failure.
-- 
-- The job identifier is 9426 and the job result is failed.
Oct 03 15:49:53 ubuntu-s-1vcpu-1gb-sfo2-01 postfix/smtpd[57644]: lost connection after EHLO from unknown[180.214.237.238]
Oct 03 15:49:53 ubuntu-s-1vcpu-1gb-sfo2-01 postfix/smtpd[57644]: disconnect from unknown[180.214.237.238] ehlo=1 commands=1`
